# Generated by Django 2.1.7 on 2019-02-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='q_no',
            field=models.IntegerField(default=0),
        ),
    ]
