# Generated by Django 2.1.5 on 2019-02-05 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email_date',
            field=models.DateField(default=datetime.date(2019, 2, 5)),
        ),
    ]
