# Generated by Django 2.1.5 on 2019-02-05 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userdata_email_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_no',
        ),
        migrations.AddField(
            model_name='userdata',
            name='post_date',
            field=models.DateField(default=datetime.date(2019, 2, 5)),
        ),
        migrations.AddField(
            model_name='userdata',
            name='q_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('prepos', 'PREPOS'), ('experiment', 'EXPERIMENT'), ('placebo', 'PLACEBO'), ('control', 'CONTROL')], max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='group',
            field=models.CharField(choices=[('prepos', 'PREPOS'), ('experiment', 'EXPERIMENT'), ('placebo', 'PLACEBO'), ('control', 'CONTROL')], max_length=450, null=True),
        ),
    ]
