# Generated by Django 2.1.5 on 2019-02-11 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190208_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice5',
            field=models.CharField(default='wsr', max_length=4500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice6',
            field=models.CharField(default='wsr', max_length=4500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice7',
            field=models.CharField(default='wsr', max_length=4500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.CharField(default='wsr', max_length=4500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.CharField(default='wsr', max_length=4500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.CharField(default='wsr', max_length=4500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.CharField(default='wsr', max_length=4500, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_date',
            field=models.DateField(default=datetime.date(2019, 2, 11)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='post_date',
            field=models.DateField(default=datetime.date(2019, 2, 11)),
        ),
    ]
