# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190211_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='state',
            field=models.CharField(default=b'Bihar', max_length=100),
        ),
    ]
