# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190211_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name=b'post_date',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_date',
            field=models.DateField(default=datetime.date(2019, 2, 13)),
        ),
    ]
